service: soracom-ping-monitoring-sample
frameworkVersion: '2 || 3'
provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  stage: dev
  lambdaHashingVersion: 20201221
plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

functions:
  code:
    handler: handler.lambda_handler
    layers:
      - arn:aws:lambda:ap-northeast-1:717257875195:layer:soracom-cli-0104:1
    timeout: 60
